language: go
sudo: required
services:
- docker
install:
- go get github.com/spf13/hugo
- sudo apt-get update
- sudo apt-get install nodejs npm
script:
- npm install && gulp build:dev
- hugo
- docker build -t waziup/website .
- docker push waziup/website
- kubectl delete -f website.yaml  --now
- kubectl apply -f website.yaml
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_23f5599cc3d3_key -iv $encrypted_23f5599cc3d3_iv -in config.enc -out ~/.kube/config -d
