language: go 
sudo: required
services:
- docker
- node_js: 6.9.0
install:
  - go get github.com/spf13/hugo
  - sudo apt-get update
  - sudo apt-get install nodejs npm
script:
  - npm install && gulp build:dev
  - hugo
notifications:
  email:
    on_failure: always
