dist: trusty
sudo: required
services:
- docker
install:
- go get github.com/spf13/hugo
#- sudo apt-get update
#- sudo apt-get install nodejs npm
script:
- npm install && gulp build:dev
- hugo
- docker build -t waziup/website .
- docker push waziup/website
- kubectl delete -f website.yaml  --now
- kubectl apply -f website.yaml
notifications:
  email:
    on_failure: always
before_install:
- mkdir ~/.kube ~/.docker
- openssl aes-256-cbc -K $encrypted_23f5599cc3d3_key -iv $encrypted_23f5599cc3d3_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv home/cdupont/.kube/config ~/.kube
- mv home/cdupont/.docker/config.json ~/.docker
- sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
- sudo add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-trusty main"
- sudo apt-get update
- sudo apt-get install -y kubectl
