language: go 
sudo: false
services:
- docker
- node_js: 6.9.0
install:
  - brew update
  - brew install hugo

script:
  - npm install && gulp build:dev
  - hugo
notifications:
  email:
    on_failure: always
