baseurl: "https://www.waziup.io"
title: "WAZIUP Platform"
languageCode: "en-us"
showVisitedLinks: true

#permalinks:
#  documentation: /:year/:month/:title/

menu:
  main:
    - identifier: forum 
      title: Forum
      pre: <i class='fa fa-external-link'></i>
      url: https://forum.waziup.io
      weight: 10
    - identifier: diy 
      title: DIY
      pre: <i class='fa fa-external-link'></i>
      url: https://diy.waziup.io
      weight: 11
    - identifier: wazihub 
      title: Wazihub
      pre: <i class='fa fa-external-link'></i>
      url: https://www.wazihub.com
      weight: 12
