baseurl = "."
theme = "waziup-theme"
metadataformat = "yaml"
canonifyurls = true

# Multilingual Mode settings
defaultContentLanguage = "en"


[Languages]
[Languages.en]
title = "WAZIUP Platform"
weight = 1
[Languages.en.params]
description = "Waziup - Cloud and IoT platform"
copyright = "Released under the Apache 2 license"


[Languages.fr]
title = "La plateforme Waziup"
weight = 2
[Languages.fr.params]
description = "Waziup - La plateforme du Cloud et de l'IoT"
copyright = "Sous licence Apache 2"


# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "waziup.io"
	
	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/Waziup/waziup.io"

	version = "0.1.0"
	logo = "images/logo-waziup.png"
	favicon = "images/logo-waziup.png"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	custom_menu = [
    "API"
  ]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "pink"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

