apiVersion: v1
kind: Pod
metadata:
  name: website
  namespace: waziup-test
  labels:
    name: website
spec:
  containers:
  - name: website
    image: waziup/website
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: waziup-test
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31334
  selector:
    name: website

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website
  namespace: waziup-test
spec:
  rules:
  - host: test.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 80

