name = "Waziup Theme"
license = "MIT"
licenselink = "https://github.com/waziup/waziup.io/blob/master/LICENSE"
description = ""
homepage = "https://github.com/waziup/waziup.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
